MODEL:
  TYPE: "resnet"
  NAME: "r50"
  WEIGHTS: ""
  THRESHOLS: 0.5

FAISS:
  FEATURE_DIM: 2048
  INDEX_TYPE: "Flat"
  INDEX_PATH: "data/resnet/resnet.index"

SQLITE:
  TABLE_NAME: "resnet"
  DB_PATH: "data/resnet/resnet.db"

MEDIA:
  MEDIA_ROOT: "D:/data/image_search"
